services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_PASSWORD=2010"
      - "POSTGRES_DB=pd421_games_store"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - db:/var/lib/postgresql
    networks:
      - pd421_gameshop

  api:
    build: back/
    image: frasp/back
    container_name: api
    environment:
      - ConnectionStrings__DefaultDb=User ID=postgres;Password=2010;Host=db;Port=5432;Database=pd421_games_store;
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5173:8080"
    volumes:
      - api:/app/storage
    networks:
      - pd421_gameshop

  front:
    build: front/
    image: frasp/front:v1.0
    container_name: front
    depends_on:
      - api
    ports:
      - "80:8080"
    networks:
      - pd421_gameshop
    environment:
      - VITE_API_BASE_URL=http://localhost:5173/api

networks:
  pd421_gameshop:
    name: "pd421_gameshop"

volumes:
  db:
    driver: local
    name: "db"
  api:
    driver: local
    name: "api"
